application: hrishihome
version: 4
runtime: python
api_version: 1

default_expiration: "2d 0h 0m"

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 )$


handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/queue/deferred
  script: deferred.py
  login: admin

- url: /twitglee.*
  script: projects/twitglee/twitglee.py

- url: /admin/.*
  script: admin.py
  login: admin

- url: /static/([^/]+)/(.*)
  static_files: themes/\1/static/\2
  upload: themes/[^/]+/static/.*

- url: /projects/([^/]+)/(.*)
  static_files: projects/\1/static/\2
  upload: projects/[^/]+/static/.*

- url: /favicon.ico
  static_files: themes/default/static/favicon.ico
  upload: themes/default/static/favicon.ico

- url: /cablemap
  static_files: projects/cablemap/index.html
  upload: projects/cablemap/index.html

- url: /cablemap/
  static_files: projects/cablemap/index.html
  upload: projects/cablemap/index.html
  

- url: /.*
  script: static.py
